name: Build and Deploy Flutter Web App

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.10.6"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Pages deployment permissions: https://stackoverflow.com/a/74167257
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b $FLUTTER_VERSION flutter
      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
      - name: Compile a clean web build
        run: |
          flutter clean
          flutter build web --base-href "/hendrix-today-uploader/"
      - name: Navigate to the new build
        run: cd build/web/
      - name: Initialize a temporary Git repo
        run: |
          git init
          git add .
          git commit -m "automated deployment commit"
      - name: Push build to the gh-pages branch
        run: git push -f https://github.com/reidst/hendrix-today-uploader.git HEAD:gh-pages
