name: Build and Deploy Flutter Web App

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.10.6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b $FLUTTER_VERSION flutter
      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
      - name: Compile a clean web build
        run: |
          flutter clean
          flutter build web --base-href "/hendrix-today-uploader/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./build/"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/deploy-pages@v2
        with:
          artifact-name: "./build/github-pages"
      - name: Deploy
        uses: actions/deploy-pages@v2
